import React from "react";
import { View, Image, Text, Button } from "react-native";
import NfcManager, { NfcTech, Ndef } from "react-native-nfc-manager";
import styles from "../../styles";
import AR4 from "../../nfc-module";

export default function Tab() {
  const [nfcResult, setNfcResult] = React.useState('');

  React.useEffect(() => {
    NfcManager.start();
  }, []);

  const scanNfc = async () => {
    try {
      // Request NfcV technology
      await NfcManager.requestTechnology(NfcTech.NfcV);
      console.log("NFCV technology acquired");

      const tag = await NfcManager.getTag();
      console.log(typeof(tag.id))

      if (!tag) {
        throw new Error('No NFC tag detected');
      }

      setNfcResult(`Tag found: ${JSON.stringify(tag)}`);
      console.log(tag);
      
      const example = new AR4();
      const payload = example.convertToByteArray(tag.id);

      console.log("Generated Byte Array:");
      console.log(payload.map(b => b.toString(16).padStart(2, '0')).join('-'));
      
      const response = await NfcManager.transceive(payload);
      console.log("Response:", response);
      setNfcResult(`Tag found: ${JSON.stringify(tag)}\nResponse: ${response}`);
      // {"techTypes":["android.nfc.tech.NfcV","android.nfc.tech.NdefFormatable"],"id":"BA8F6F0E672402E0"}
    } catch (error) {
      setNfcResult(`Error: ${error.message}`);
      console.error("Error:", error);
    } finally {
      NfcManager.cancelTechnologyRequest();
    }
  };
  return (
    <View style={[styles.container, styles.centered]}>
      <Text style={styles.statusText}>4 start times</Text>
      <View style={styles.nfcIcon}>
        <Image
          source={require("../../assets/nfc_logo.png")}
          style={styles.nfcImage}
        />
      </View>
      <View style={styles.buttonContainer}>
        <Button title="CONNECT & UPDATE" onPress={scanNfc} />
      </View>
      <Text style={styles.nfcResult}>{nfcResult}</Text>
    </View>
  );
}
