update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean")
    gradle(task: "app:bundleRelease")
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
    )
  end
end
